version: "3.8"
services:
  web:
   image: 'gitlab/gitlab-ce:latest'
   restart: always
   hostname: 'gitlab.${DOMAIN?Variable not set}'
   ports:
     - '80:80'
     - '443:443'
   volumes:
     - './gitlab/configs:/etc/gitlab'
     - './gitlab/logs:/var/log/gitlab'
     - './gitlab/data:/var/opt/gitlab'
   networks:
     - traefik-public
   deploy:
     placement:
       constraints:
         - node.labels.gitlab.gitlab-data == true
     labels:
       - traefik.enable=true
       - traefik.docker.network=traefik-public
       - traefik.constraint-label=traefik-public
       - traefik.http.routers.gitlab-http.rule=Host(`gitlab.${DOMAIN?Variable not set}`)
       - traefik.http.routers.gitlab-http.entrypoints=http
       - traefik.http.routers.gitlab-http.middlewares=https-redirect
       - traefik.http.routers.gitlab-https.rule=Host(`gitlab.${DOMAIN?Variable not set}`)
       - traefik.http.routers.gitlab-https.entrypoints=https
       - traefik.http.routers.gitlab-https.tls=true
       - traefik.http.routers.gitlab-https.tls.certresolver=le
       - traefik.http.services.gitlab.loadbalancer.server.port=80

networks:
 traefik-public:
   external: true
