version: '3.8'

services:
  # The GitLab container itself
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.${DOMAIN?Variable not set}'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.${DOMAIN?Variable not set}'
        nginx['listen_https'] = false
        nginx['listen_port'] = 80
        gitlab_rails['backup_upload_remote_directory'] = 's3-backup-bucket'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.${DOMAIN?Variable not set}"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "gitlab@${DOMAIN?Variable not set}"
        gitlab_rails['smtp_password'] = "${PASSWORD?Variable not set}"
        gitlab_rails['smtp_domain'] = "${DOMAIN?Variable not set}"
        gitlab_rails['smtp_authentication'] = "plain"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['gitlab_shell_ssh_port'] = 22
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitlab_insecure.entrypoints=web
      - traefik.http.routers.gitlab_insecure.rule=Host(`gitlab.${DOMAIN?Variable not set}`)
      - traefik.http.routers.gitlab_insecure.middlewares=redirect@file

      - traefik.http.routers.gitlab.entrypoints=web-secure
      - traefik.http.routers.gitlab.rule=Host(`gitlab.${DOMAIN?Variable not set}`)
      - traefik.http.routers.gitlab.tls.certresolver=letsencrypt
      - traefik.http.services.gitlab.loadbalancer.server.port=80
      - traefik.docker.network=traefik-public

      # Can't filter TCP traffic on SNI, see link below
      # https://community.containo.us/t/routing-ssh-traffic-with-traefik-v2/717/6
      - traefik.tcp.routers.gitlab-ssh.rule=HostSNI(`*`)
      - traefik.tcp.routers.gitlab-ssh.entrypoints=ssh
      - traefik.tcp.routers.gitlab-ssh.service=gitlab-ssh-svc
      - traefik.tcp.services.gitlab-ssh-svc.loadbalancer.server.port=22

networks:
  traefik-public:
    external: true
