version: '3.3'

services:		

   db:
     image: postgres
     networks:	
        - nextcloud_nextcloud_network
     volumes:
        - .db-data:/var/lib/postgresql/data  
     environment:
        - POSTGRES_USER: 'postgres'
         

   app:
     image: nextcloud:latest
     depends_on:
        - db
     volumes:
        - nfsDATA:/var/www/html	
     networks:
        - traefik-public
        - nextcloud_nextcloud_network
     environment:
        - POSTGRES_DB: 'nextcloud'     
        - POSTGRES_USER: 'postgres'
        - POSTGRES_HOST: 'db'
        - NEXTCLOUD_ADMIN_USER: $USERNAME
        - NEXTCLOUD_ADMIN_USER: admin
        
     labels:
        - traefik.frontend.rule=Host:${DOMAIN?Variable DOMAIN not set}
        - traefik.enable=true
        - traefik.port=9000
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https

networks:
    traefik-public:
      external: true
    nextcloud_nextcloud_network:
      external: true 
 
volumes:
    nfsDATA:
      external: true
