version: '3.3'

services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    volumes:
        - ./registry-data:/var/lib/registry
        - ./certs:/certs
        - ./auth:/auth

    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.labels.registry == true
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.registry-http.rule=Host(`${REGISTRY_DOMAIN?Variable not set}`)
        - traefik.http.routers.registry-http.entrypoints=http
        - traefik.http.routers.registry-http.middlewares=https-redirect
        - traefik.http.routers.registry-https.rule=Host(`${REGISTRY_DOMAIN?Variable not set}`)
        - traefik.http.routers.registry-https.entrypoints=https
        - traefik.http.routers.registry-https.tls=true
        - traefik.http.routers.registry-https.tls.certresolver=le
        - traefik.http.services.registry.loadbalancer.server.port=5000

networks:
  traefik-public:
    external: true
