version: '3.7'

services:
  db:
    image: mysql
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: darthjuda
      MYSQL_DATABASE: icm
      MYSQL_ROOT_PASSWORD: $PASSWORD
      MYSQL_PASSWORD: $PASSWORD
    networks:
      - dbnet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: ./data/mysql
        target: /var/lib/mysql

networks:
  dbnet:
    external: true
