version: '3.7'

services:
  db:
    image: mysql
    secrets:
      - db_root_password
      - db_dba_password
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: darthjuda
      MYSQL_DATABASE: icm
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_dba_password
    networks:
      - dbnet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: ./data/mysql
        target: /var/lib/mysql

secrets:
  db_root_password:
    external: true
  db_dba_password:
    external: true

networks:
  dbnet:
    external: true
